title: Faxbot
description: The first open-source, self-hostable fax API with AI integration
baseurl: "/Faxbot"
url: "https://dmontgomery40.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /Faxbot/docs/assets/images/faxbot_full_logo.png

# External links
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/dmontgomery40/Faxbot
    hide_icon: false

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Table of contents
nav_sort: case_insensitive
nav_fold: false

# Footer
footer_content: "Copyright &copy; 2024 Faxbot. Distributed under the <a href=\"https://github.com/dmontgomery40/Faxbot/blob/main/LICENSE\">MIT License</a>."

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Excludes
exclude:
  - node_modules/
  - docs/_site/
  - api/
  - asterisk/
  - python_mcp/
  - node_mcp/
  - sdks/
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - Rakefile
  # Exclude legacy single-file docs to keep sidebar clean
  - docs/API_REFERENCE.md
  - docs/MCP_INTEGRATION.md
  - docs/PHAXIO_E2E_TEST.md
  - docs/PHAXIO_SETUP.md
  - docs/SINCH_SETUP.md
  - docs/SIP_SETUP.md
  - docs/SDKS.md
  - docs/OAUTH_SETUP.md
  - docs/IMAGES_AND_PDFS.md
  - docs/TROUBLESHOOTING.md
  - docs/HIPAA_REQUIREMENTS.md
  # Exclude root Markdown that should not be in the nav
  - AGENTS.md
  - HIPAA_REQUIREMENTS.md
  - OCR_WORKAROUND_IMPLEMENTATION.md
  - TODO.md

