version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - FAX_DATA_DIR=/faxdata
    volumes:
      - faxdata:/faxdata
    ports:
      - "8080:8080"
    # Note: Asterisk dependency is optional - only needed for SIP backend

  # Asterisk service - only needed for SIP backend
  # Can be disabled by setting FAX_BACKEND=phaxio in .env (cloud backend)
  asterisk:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - faxdata:/faxdata
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5038:5038" # AMI
      - "4000-4999:4000-4999/udp" # UDPTL for T.38

  # Optional: Faxbot MCP Server for AI integration
  faxbot-mcp:
    build:
      context: ./node_mcp
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - FAX_API_URL=http://api:8080
      - API_KEY=${API_KEY}
    depends_on:
      - api
    ports:
      - "3001:3001"
    profiles:
      - mcp
    stdin_open: true
    tty: true

  # Optional: Faxbot MCP SSE (OAuth2/JWT) for HIPAA-grade integrations
  faxbot-mcp-sse:
    build:
      context: ./node_mcp
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - FAX_API_URL=http://api:8080
      - API_KEY=${API_KEY}
      - OAUTH_ISSUER=${OAUTH_ISSUER}
      - OAUTH_AUDIENCE=${OAUTH_AUDIENCE}
      - OAUTH_JWKS_URL=${OAUTH_JWKS_URL}
      - MCP_SSE_PORT=3002
    command: ["node", "src/servers/sse.js"]
    depends_on:
      - api
    ports:
      - "3002:3002"
    profiles:
      - mcp
    stdin_open: true
    tty: true

  # Optional: Python MCP SSE (OAuth2/JWT). Alternative to Node SSE.
  faxbot-mcp-py-sse:
    build:
      context: ./python_mcp
      dockerfile: Dockerfile.sse
    env_file:
      - ./.env
    environment:
      - FAX_API_URL=http://api:8080
      - API_KEY=${API_KEY}
      - OAUTH_ISSUER=${OAUTH_ISSUER}
      - OAUTH_AUDIENCE=${OAUTH_AUDIENCE}
      - OAUTH_JWKS_URL=${OAUTH_JWKS_URL}
    depends_on:
      - api
    ports:
      - "3003:3003"
    profiles:
      - mcp
    stdin_open: true
    tty: true

  # Optional: MCP Inspector (web UI) to explore tools/resources/prompts
  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    ports:
      - "6274:6274"  # UI
      - "6277:6277"  # Proxy
    profiles:
      - mcp
    stdin_open: true
    tty: true

volumes:
  faxdata:
    driver: local
