name: FaxbotApp
options:
  minimumXcodeGenVersion: 2.32.0
  deploymentTarget:
    iOS: "26.0"
targets:
  Faxbot:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Faxbot
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.faxbot.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: NO
        SWIFT_VERSION: 5.10
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        CODE_SIGN_ENTITLEMENTS: Resources/Faxbot.entitlements
        # Enhanced Security build settings (iOS 26)
        ENABLE_POINTER_AUTHENTICATION: YES
        CLANG_ENABLE_C_TYPED_ALLOCATOR_SUPPORT: YES
        CLANG_ENABLE_CPLUSPLUS_TYPED_ALLOCATOR_SUPPORT: YES
        CLANG_ENABLE_STACK_ZERO_INIT: YES
        ENABLE_SECURITY_COMPILER_WARNINGS: YES
        ENABLE_C_BOUNDS_SAFETY: YES
        ENABLE_CPLUSPLUS_BOUNDS_SAFE_BUFFERS: YES
        # Enable modern UI effects; actual LiquidGlass APIs are used in code where possible
        UISupportedInterfaceOrientations_iPhone: [UIInterfaceOrientationPortrait]
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: Faxbot
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Automatic
        NSCameraUsageDescription: "Camera is used to scan documents and QR pairing codes."
        NSPhotoLibraryAddUsageDescription: "Photos access is used to share or attach images to faxes."
        NSLocalNetworkUsageDescription: "Local network is used to discover your Faxbot server on your LAN."
        UIRequiresFullScreen: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
  FaxbotShare:
    type: app-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/FaxbotShare
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: net.faxbot.ios.share
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.10
        APPLICATION_EXTENSION_API_ONLY: YES
        CODE_SIGN_ENTITLEMENTS: Resources/FaxbotShare.entitlements
    info:
      path: Resources/ShareExtensionInfo.plist
      properties:
        CFBundleName: FaxbotShare
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
    dependencies:
      - target: Faxbot
aggregateTargets: []
schemes:
  Faxbot:
    build:
      targets:
        Faxbot: all
    run:
      config: Debug
  FaxbotShare:
    build:
      targets:
        FaxbotShare: all
    run:
      config: Debug
