"""Print docs/reference/cli.md, generated from the command definitions with Typer's Markdown docs.

Run ``python -m app.cli.reference > ../docs/reference/cli.md`` from the API
directory, or ``make cli-docs`` from the repository root.
"""
import sys

import typer.main
from typer.cli import MARKUP_MODE_KEY, get_docs_for_click
from typer.models import Context

from .main import app
from .nouns import MOVED

INTRODUCTION = (
    '<!-- Generated by `make cli-docs` from api/app/cli. Do not edit by hand. -->\n\n'
    'Every `faxbot` command, its options and arguments, generated from the command definitions. '
    'For installation, profiles, scripting and owner recovery, see [Command line](../operations/cli.md).\n\n'
)


OLDER_NAMES = (
    '## Older command names\n\n'
    'Commands from earlier versions still work but are not listed in help. Each one runs the command next to it.\n\n'
    '| Older command | Now |\n| --- | --- |\n'
)


def visible(command):
    """A freshly built command tree without its hidden commands, all the way down."""
    if isinstance(getattr(command, 'commands', None), dict):
        command.commands = {name: visible(sub) for name, sub in command.commands.items() if not sub.hidden}
    return command


def render():
    command = visible(typer.main.get_command(app))
    context = Context(command, info_name='faxbot')
    context.obj = {MARKUP_MODE_KEY: app.rich_markup_mode}
    body = get_docs_for_click(obj=command, ctx=context, name='faxbot', title='Command line reference')
    title, _, rest = body.strip().partition('\n')
    older = ''.join(f"| `faxbot {' '.join(old)}` | `faxbot {' '.join(new)}` |\n" for old, new in sorted(MOVED.items()))
    return f'{title}\n\n{INTRODUCTION}{rest.strip()}\n\n{OLDER_NAMES}{older}'


if __name__ == '__main__':
    sys.stdout.write(render())
