title: Faxbot
description: The first open-source, self-hostable fax API with AI integration
baseurl: "/Faxbot"
url: "https://dmontgomery40.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /Faxbot/docs/assets/images/faxbot_full_logo.png

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/dmontgomery40/Faxbot
    hide_icon: false

# Table of contents
nav_sort: case_insensitive
nav_fold: false

# Footer
footer_content: "Copyright &copy; 2024 Faxbot. Distributed under the <a href=\"https://github.com/dmontgomery40/Faxbot/blob/main/LICENSE\">MIT License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Last edit timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Google Analytics (replace with your tracking ID)
# ga_tracking: G-XXXXXXXXXX

# Callouts (for alerts, warnings, etc.)
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

# Mermaid diagrams
mermaid:
  version: "9.4.0"

# Code copy button
enable_copy_code_button: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
