name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript
      - name: Install Python deps
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          FAX_DISABLED: 'true'
          FAX_DATA_DIR: './faxdata'
          DATABASE_URL: 'sqlite:///./test_faxbot_ci.db'
        working-directory: api
        run: |
          mkdir -p faxdata
          pytest -q
